# Generated by Django 5.2.3 on 2025-06-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='job_city',
            field=models.CharField(default='To be selected', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profileimg'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
