# Generated by Django 5.2.3 on 2025-06-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_application_email_application_job_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_city',
            field=models.JSONField(default=list),
        ),
    ]
